### ISSUE TITLE
replace URI with addressable

### ISSUE THREAD

**Issue by atomotic** [code4lib/ruby-oai#26]
what do you think about  replacing URI  with addressable?
often i deal with domain containing "_" (that violates RFC 1034 supported by URI)

https://github.com/code4lib/ruby-oai/blob/master/lib/oai/client.rb#L85

```
require 'addressable/uri'
@base = Addressable::URI.parse base_url
```

ciao

**Comment by barmintor** [comment]
Thank you for this report - I'm sorry it was never addressed.

Per https://bugs.ruby-lang.org/issues/8241, Ruby's core URI parse has supported this behavior since Ruby 2.2, and this library currently requires Ruby >= 2.6.
