### ISSUE TITLE
:follow_redirects is not registered on Faraday::Response

### ISSUE THREAD

**Issue by belousovAV** [code4lib/ruby-oai#35]
ruby 2.1.1
faraday (0.9.0, 0.9.0.rc7)
oai (0.3.1)

Example:

`require 'oai'
  client = OAI::Client.new 'http://www.pubmedcentral.gov/oai/oai.cgi'`

Result:
`/usr/local/rvm/gems/ruby-2.1.1/gems/faraday-0.9.0.rc7/lib/faraday.rb:189:in lookup_middleware: :follow_redirects is not registered on Faraday::Response (Faraday::Error)
        from /usr/local/rvm/gems/ruby-2.1.1/gems/faraday-0.9.0.rc7/lib/faraday/rack_builder.rb:203:in use_symbol'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/faraday-0.9.0.rc7/lib/faraday/rack_builder.rb:96:in response'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/oai-0.3.1/lib/oai/client.rb:98:in block (2 levels) in initialize'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/faraday-0.9.0.rc7/lib/faraday/connection.rb:91:in initialize'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/faraday-0.9.0.rc7/lib/faraday.rb:70:in new'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/faraday-0.9.0.rc7/lib/faraday.rb:70:in new'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/oai-0.3.1/lib/oai/client.rb:92:in block in initialize'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/oai-0.3.1/lib/oai/client.rb:91:in fetch'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/oai-0.3.1/lib/oai/client.rb:91:in initialize'
        from oai-pmh.rb:2:in new'
        from oai-pmh.rb:2:in <main>'`

**Comment by dmolesUC3** [comment]
I'm not seeing this with faraday 0.9.1 and ruby 2.2.1.

**Comment by belousovAV** [comment]
ruby 2.2.1, faraday 0.9.1
All is well.
