### ISSUE TITLE
Get Raw XML from Record (?)

### ISSUE THREAD

**Issue by no-reply** [code4lib/ruby-oai#41]
I am running ListRecords requests via the client and need to store the xml of the individual `<record>`s.  Record stores the contents of the `header`, `metadata`, and `about` tags separately, which means that I have to rebuild the record from its parts.

Is there a better way I should be doing this?  Should `OAI::Record` store the raw XML and build its parts on the fly?

**Comment by dmolesUC3** [comment]
I haven't tried, but looking at [`ListRecordsResponse`](https://github.com/code4lib/ruby-oai/blob/master/lib/oai/client/list_records.rb) it seems like you ought to be able to get at the raw OAI response via the `@doc` attribute and make the same kind of XPath query as the `each` method to bypass `Record` and get directly at the `<record>`s.
