### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by no-reply** [code4lib/ruby-oai#46]
This gem has been fairly stable over the last year or so, and it seems like a good idea to push it to 1.0. Before doing that, it would be a good idea to:
- have some current users audit the APIs to identify potential blockers
- determine which Ruby versions and environments are considered supported
- turn on CI
- improve documentation

Any takers on helping to organize and/or do some of this work?

**Comment by kelynch** [comment]
:+1: Count me in.

**Comment by Coren** [comment]
:+1:

**Comment by jrochkind** [comment]
I don't believe much if any of this has been done in the past 4 years. 

I am doing some (but not all) of it now, and will be doing a 1.0 release. 

We will get CI; and determined supported ruby versions (probably very different than 4 years ago), at least as defined by what CI tests. 

If anyone else still wants to improve documentation or audit the APIs, that would be quite welcome! i don't now if @kelynch or @Coren are still working this area. 

But I plan to do a 1.0 release regardless, 4 years is long enough to wait!

**Comment by jrochkind** [comment]
closing as obsolete, see other tickets.
