### ISSUE TITLE
Error installing from rubygems - RDoc not buidling.

### ISSUE THREAD

**Issue by bibliotechy** [code4lib/ruby-oai#51]
Looks like it is only an issue with building the docs. If I run `gem install --no-ri` it builds cleanly.

Error output below:

Fetching: builder-3.2.2.gem (100%)
Successfully installed builder-3.2.2
Fetching: oai-0.4.0.gem (100%)
Successfully installed oai-0.4.0
Parsing documentation for builder-3.2.2
Installing ri documentation for builder-3.2.2
Parsing documentation for oai-0.4.0

RDoc::Parser::Ruby failure around line 28 of
lib/oai/harvester/logging.rb

Before reporting this, could you check that the file you're documenting
has proper syntax:

  /Users/chad/.rvm/rubies/ruby-2.2.2/bin/ruby -c lib/oai/harvester/logging.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

```
(NoMethodError) undefined method `name' for {TkNL 852, 27:28 "\n"}:RDoc::RubyToken::TkNL
```

ERROR:  While executing gem ... (NoMethodError)
    undefined method `name' for {TkNL 852, 27:28 "\n"}:RDoc::RubyToken::TkNL

**Comment by techgique** [comment]
Confirming: `gem install --no-ri oai` succeeds

**Comment by barmintor** [comment]
This was probably fixed in https://github.com/code4lib/ruby-oai/commit/4acd9d40590a8932df73462edfc63a567b2a8afa and will go into the next release.

**Comment by barmintor** [comment]
Fix is released! https://github.com/code4lib/ruby-oai/releases/tag/v1.2.0
