### ISSUE TITLE
Release version 1.0.0

### ISSUE THREAD

**Issue by jrochkind** [code4lib/ruby-oai#77]
Version 1.0.0.beta1 has been released!

If I hear nothing else, I will release it no earlier than one week from today (Tuesday September 3rd), or no later than... when I remember to. 

But I am happy to wait longer than that for a 1.0.0 release if there are people who want to test it or look at it and want more time, no problem at all, just let me know! I'd love to have people testing and looking at it!

This ticket is to remind me/us that if we haven't heard anything, and it's after September 3 2019, it's time to release 1.0.0. :)

**Comment by tpendragon** [comment]
@jrochkind It's after September 3, 2019

**Comment by jrochkind** [comment]
Thanks for ping, I will do a release! 

(Also if anyone else is interested in being a committer, let us know!)

**Comment by jrochkind** [comment]
1.0.0 is released, from current master! I believe it is equivalent to 1.0.0.beta1.
