### ISSUE TITLE
Exception using list_records.full

### ISSUE THREAD

**Issue by yulgit1** [code4lib/ruby-oai#83]
Running the method:
client.list_records(:metadata_prefix => 'marc21').full.count

And getting Exception:
OAI::Exception: either 'metadataPrefix' or 'resumptionToken' is required

Full stack trace:
https://gist.github.com/yulgit1/9a39d0244b3accf6479cb216838588ef

I believe it is occurring at the end, as when I do a list_records.full of a repo with ~60 k objects (which takes ~30 minutes), this error occurs after ~59000.

I also suspect this line:
https://github.com/code4lib/ruby-oai/blob/master/lib/oai/client.rb#L219
where perhaps the last resumption of course won't have a resumption token, but no metadataPrefix is passed either.  But I'm not certain.  I'm having difficulty testing the gem for this, but posting this issue in case anyone has any insight.

**Comment by barmintor** [comment]
Closing pending further information.
